"""Add phone and salary to users

Revision ID: 92434a0a9855
Revises: b53e31f34f55
Create Date: 2026-04-25 12:15:40.335087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92434a0a9855'
down_revision = 'b53e31f34f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salary')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
