"""Add last_billing_date column to Tenant

Revision ID: cf3b4a7e9eae
Revises: a5b8a997522c
Create Date: 2026-05-18 12:14:37.242060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3b4a7e9eae'
down_revision = 'a5b8a997522c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_billing_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('last_billing_date')

    # ### end Alembic commands ###
