"""Add attachment to sales and purchases

Revision ID: a5234fdc6f25
Revises: 92434a0a9855
Create Date: 2026-04-25 12:31:46.550320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5234fdc6f25'
down_revision = '92434a0a9855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
