"""Add CustomerGroup model and link it to Customer

Revision ID: cc0293142c0d
Revises: cf3b4a7e9eae
Create Date: 2026-05-18 12:40:04.272299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0293142c0d'
down_revision = 'cf3b4a7e9eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'customer_groups', ['customer_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_group_id')

    # ### end Alembic commands ###
