"""Add payment_method to fuel_deliveries

Revision ID: f49923a5070f
Revises: j3k7f5g8h0i1
Create Date: 2026-06-22 10:40:30.451793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49923a5070f'
down_revision = 'j3k7f5g8h0i1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('attendant_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date', 'shift_number', 'tenant_id', name='uq_fuel_shift')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_shift_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fuel_day_close_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fuel_day_closes', ['fuel_day_close_id'], ['id'])
        batch_op.create_foreign_key(None, 'fuel_shifts', ['fuel_shift_id'], ['id'])

    with op.batch_alter_table('fuel_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    with op.batch_alter_table('fuel_pump_shift_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['attendant_id'], ['id'])

    with op.batch_alter_table('fuel_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fuel_shifts', ['fuel_shift_id'], ['id'])

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fuel_shifts', ['fuel_shift_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fuel_shift_id')

    with op.batch_alter_table('fuel_sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fuel_shift_id')

    with op.batch_alter_table('fuel_pump_shift_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attendant_id')

    with op.batch_alter_table('fuel_deliveries', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fuel_day_close_id')
        batch_op.drop_column('fuel_shift_id')

    op.drop_table('fuel_shifts')
    # ### end Alembic commands ###
